type Exif = {
  bigEndian: false,
  Image: {
    ImageWidth: number; // e.g.,: number; // e.g.,: 2372,
    ImageLength: number; // e.g.,: 2980,
    // BitsPerSample: [ 8, 8, 8 ],
    PhotometricInterpretation: number; // e.g.,: 2,
    Make: string; // e.g.,: "Canon",
    Model: string; // e.g.,: "MG5200 series",
    Orientation: number; // e.g.,: 1,
    SamplesPerPixel: number; // e.g.,: 3,
    XResolution: number; // e.g.,: 300,
    YResolution: number; // e.g.,: 300,
    ResolutionUnit: number; // e.g.,: 2,
    Software: string; // e.g.,: "Adobe Photoshop CS6 (Windows)",
    DateTime: Date; // e.g.,: 2019-03-14T19:18:10.000Z,
    YCbCrPositioning: number; // e.g.,: 1,
    ExifTag: number; // e.g.,: 288,
  },
  Thumbnail: {
    Compression: number; // e.g.,: 6,
    XResolution: number; // e.g.,: 72,
    YResolution: number; // e.g.,: 72,
    ResolutionUnit: number; // e.g.,: 2,
    JPEGInterchangeFormat: number; // e.g.,: 518,
    JPEGInterchangeFormatLength: number; // e.g.,: 6814,
  },
  Photo: {
    // ExifVersion: <Buffer 30 32 32 31>,
    DateTimeDigitized: Date; // e.g.,: 2019-03-14T12:30:41.000Z,
    // ComponentsConfiguration: <Buffer 01 02 03 00>,
    // FlashpixVersion: <Buffer 30 31 30 30>,
    ColorSpace: number; // e.g.,: 1,
    PixelXDimension: number; // e.g.,: 2361,
    PixelYDimension: number; // e.g.,: 2966,
    // FileSource: <Buffer 02>,
    WhiteBalance: number; // e.g.,: 0,
  },
}